steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/bobgourmet-backend:latest',
      '.'
    ]

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/bobgourmet-backend:latest'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'bobgourmet-backend',
      '--image', 'gcr.io/$PROJECT_ID/bobgourmet-backend:latest',
      '--region', 'asia-northeast3',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--set-env-vars', 'SPRING_PROFILES_ACTIVE=cloud,DATABASE_URL=jdbc:postgresql://34.47.69.25:5432/bobgourmet,DATABASE_USERNAME=bobgourmet-user,DATABASE_PASSWORD=YourSecurePassword123,REDIS_HOST=10.222.169.227,JWT_SECRET=mySecretKey1234567890123456789012345678901234567890'
    ]

images:
  - 'gcr.io/$PROJECT_ID/bobgourmet-backend:latest'